name: cloudmate
description: Cloudmate - An open-source online learning platform built with Flutter. Create classes, quizzes, and assignments, take attendance, and communicate with students. Easy to install and use.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+4

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^7.2.0
  flutter_isolate: ^2.0.0
  get_it: ^7.2.0
  socket_io_client: ^2.0.0

  # Utils
  i18n_extension: ^9.0.2
  intl: ^0.18.0
  get_storage: ^2.0.3
  ezanimation: ^0.5.0
  timeline_tile: ^2.0.0
  percent_indicator: ^3.0.1
  lottie: ^1.2.0
  fl_chart: ^0.40.2
  flutter_datetime_picker_plus: ^2.0.1
  csv: ^5.0.1
  get: ^4.3.8
  device_info: ^2.0.3
  permission_handler: ^10.1.0
  # downloads_path_provider: ^0.1.0
  file_picker: ^4.2.7

  # Firebase
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0

  # Image
  cached_network_image: ^3.1.0
  image_picker: ^0.8.6

  # Icon
  like_button: ^2.0.3
  phosphor_flutter: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  # flutter_icons: ^1.1.0

  #Payment
  momo_vn:
    git: https://github.com/Askany-NDN/momo.vn.git

  # Audio
  just_audio: ^0.9.20
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  mockito: ^5.0.15
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/launcher_icon.png"
  remove_alpha_ios: false

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/splash.json
    - assets/lottie/cat_sleeping.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Allison
      fonts:
        - asset: assets/fonts/Allison-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
